services:
  identity.postgres:
    image: postgres:15
    container_name: identity_postgres
    environment:
      POSTGRES_DB: IdentityDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: YourStrong!Password
    ports:
      - "5433:5432"
    volumes:
      - identity_postgres_data:/var/lib/postgresql/data

  identity.service:
    build: .
    container_name: identity_service
    ports:
      - "5000:80"
    depends_on:
      - identity.postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=identity.postgres;Port=5432;Database=IdentityDb;Username=admin;Password=YourStrong!Password

volumes:
  identity_postgres_data: