server {
  listen 80;
  
  # Если есть эта строка — удалите или измените
  # add_header Content-Security-Policy "script-src 'self'";
  
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}