services:
  postgres:
    image: postgres:16
    container_name: truckyeah_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: truckyeah_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@truckyeah.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:

