// <auto-generated />
using System;
using ListingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingService.Infrastructure.Migrations
{
    [DbContext(typeof(ListingServiceDbContext))]
    [Migration("20260618122222_AddListingRoutesAndGeometry")]
    partial class AddListingRoutesAndGeometry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListingService.Domain.Models.RoutePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TruckId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CargoId", "Order");

                    b.HasIndex("TruckId", "Order");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoBidEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrierUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("Status");

                    b.HasIndex("CargoId", "CarrierUserId");

                    b.ToTable("CargoBids");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedBidId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBargaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("BiddingClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("BiddingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BodyTypeRequired")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("BoostToTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("BoostedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsADR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double?>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoadingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MinBidStep")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PackagingType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PalletsCount")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrepaymentPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresCMR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresTIR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresTwoDrivers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RouteCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("RouteDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("RouteDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("RouteFuelLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("RouteGeometryGeoJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UnloadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseAutomaticCalculation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Exchange");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision");

                    b.Property<double?>("WeightPerPackageKg")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightTons")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBidId");

                    b.HasIndex("BiddingEnabled");

                    b.HasIndex("LoadDateTime");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("Visibility");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.TruckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalEquipment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("AllowBargaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CapacityTons")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CrewDriversCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LoadingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrepaymentPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RouteCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("RouteDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("RouteDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("RouteFuelLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("RouteGeometryGeoJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Exchange");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvailableFrom");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("Visibility");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("ListingService.Domain.Models.RoutePoint", b =>
                {
                    b.HasOne("ListingService.Infrastructure.Entities.CargoEntity", null)
                        .WithMany("RoutePoints")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ListingService.Infrastructure.Entities.TruckEntity", null)
                        .WithMany("RoutePoints")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoBidEntity", b =>
                {
                    b.HasOne("ListingService.Infrastructure.Entities.CargoEntity", "Cargo")
                        .WithMany("Bids")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoEntity", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.TruckEntity", b =>
                {
                    b.Navigation("RoutePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
