// <auto-generated />
using System;
using ListingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingService.Infrastructure.Migrations
{
    [DbContext(typeof(ListingServiceDbContext))]
    [Migration("20260526135328_UpdateSchema_Initial")]
    partial class UpdateSchema_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListingService.Domain.Models.RoutePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CargoEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CargoEntityId");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBargaining")
                        .HasColumnType("boolean");

                    b.Property<string>("BodyTypeRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BoostToTop")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BoostedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsADR")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<double?>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoadingType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PackagingType")
                        .HasColumnType("text");

                    b.Property<int?>("PalletsCount")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrepaymentPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresCMR")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresTIR")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnloadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightTons")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.TruckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBargaining")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CapacityTons")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LoadingType")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrepaymentPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("ListingService.Domain.Models.RoutePoint", b =>
                {
                    b.HasOne("ListingService.Infrastructure.Entities.CargoEntity", null)
                        .WithMany("RoutePoints")
                        .HasForeignKey("CargoEntityId");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoEntity", b =>
                {
                    b.Navigation("RoutePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
