// <auto-generated />
using System;
using ListingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingService.Infrastructure.Migrations
{
    [DbContext(typeof(ListingServiceDbContext))]
    partial class ListingServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListingService.Infrastructure.Entities.CargoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VolumeM3")
                        .HasColumnType("double precision");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ListingService.Infrastructure.Entities.TruckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CapacityKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PricePerKm")
                        .HasColumnType("numeric");

                    b.Property<int?>("RadiusKm")
                        .HasColumnType("integer");

                    b.Property<string>("RouteFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VolumeM3")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
