// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteService.Infrastructure;

#nullable disable

namespace RouteService.Infrastructure.Migrations
{
    [DbContext(typeof(RouteServiceDbContext))]
    [Migration("20260617134804_InitRouteService")]
    partial class InitRouteService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteService.Domain.Models.ResolvedRoutePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteCalculationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RouteCalculationId", "Order");

                    b.ToTable("ResolvedRoutePoints");
                });

            modelBuilder.Entity("RouteService.Domain.Models.RouteCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FuelConsumptionLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("Geometry")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TollRoadsStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unknown");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RequestHash")
                        .IsUnique();

                    b.ToTable("RouteCalculations");
                });

            modelBuilder.Entity("RouteService.Domain.Models.ResolvedRoutePoint", b =>
                {
                    b.HasOne("RouteService.Domain.Models.RouteCalculation", null)
                        .WithMany("ResolvedPoints")
                        .HasForeignKey("RouteCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteService.Domain.Models.RouteCalculation", b =>
                {
                    b.Navigation("ResolvedPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
